#!/usr/bin/env bash

UBUNTU_RELEASE_CODENAME="$(lsb_release -cs)"

# bashrc
bash "ubuntu/bashrc/set-lc_all-variable.sh"

# curl
sudo bash "ubuntu/curl/install-curl.sh"

# fzf
bash "ubuntu/fzf/install-fzf.sh"

# git
sudo bash "ubuntu/git/install-git.sh"

# graphviz
sudo bash "ubuntu/graphviz/install-graphviz.sh"

# imagemagick
sudo bash "ubuntu/imagemagick/install-imagemagick.sh"

# mc
sudo bash "ubuntu/mc/install-mc.sh"

# mongodb
sudo bash "ubuntu/mongodb/install-mongodb.sh" 3.2 $UBUNTU_RELEASE_CODENAME

# mysql
sudo bash "ubuntu/mysql/install-mysql.sh" admin libmysqlclient-dev

# nmap
sudo bash "ubuntu/nmap/install-nmap.sh"

# nodejs
bash "ubuntu/nodejs/install-nvm.sh" 0.31.7
bash "ubuntu/nodejs/install-nodejs.sh" 4.5.0
bash "ubuntu/nodejs/install-nodejs.sh" 5.12.0
bash "ubuntu/nodejs/install-nodejs.sh" 6.5.0

# phantomjs
sudo bash "ubuntu/phantomjs/install-phantomjs.sh"

# postgresql
sudo bash "ubuntu/postgresql/install-postgresql.sh" 9.5 $UBUNTU_RELEASE_CODENAME libpq-dev
sudo bash "ubuntu/postgresql/create-user.sh" root admin

# redis
sudo bash "ubuntu/redis/install-redis.sh"

#ruby
bash "ubuntu/ruby/install-rvm.sh" stable
bash "ubuntu/ruby/install-ruby.sh" 1.9.3 bundler
bash "ubuntu/ruby/install-ruby.sh" 2.0.0 bundler
bash "ubuntu/ruby/install-ruby.sh" 2.1.9 bundler
bash "ubuntu/ruby/install-ruby.sh" 2.2.5 bundler
bash "ubuntu/ruby/install-ruby.sh" 2.3.1 bundler rails rubocop

# sqlite3
sudo bash "ubuntu/sqlite3/install-sqlite3.sh" libsqlite3-dev

# ssh
sudo bash "ubuntu/ssh/install-openssh-client.sh"
sudo bash "ubuntu/ssh/install-openssh-server.sh"

# the_silver_searcher
sudo bash "ubuntu/the_silver_searcher/install-the_silver_searcher.sh"

# tmux
sudo bash "ubuntu/tmux/install-tmux.sh"

# vagrant
sudo bash "ubuntu/vagrant/install-vagrant.sh" 1.8.5

# vim
sudo bash "ubuntu/vim/install-vim.sh"
bash "ubuntu/vim/install-dotvim.sh"
bash "ubuntu/vim/set-vim-as-default-editor.sh"

echo ""
echo "Running: \`source \"$HOME/.bashrc\"\`"
source "$HOME/.bashrc"
echo ""
echo "==================================================="
echo "i-vagrant: https://github.com/bogdanvlviv/i-vagrant"
echo "==================================================="
echo ""
